version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # RabbitMQ Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    user: "1000:1000"
    command: celery -A tasks.app worker --loglevel=info --concurrency=2
    env_file: [.env]
    volumes:
      - "${DATA_DIR}:/data"
      - ./tasks:/app/tasks
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: [default]

  flower:
    image: mher/flower
    command: ["celery","--broker=${BROKER_URL}","flower","--port=5555"]
    ports: ["5555:5555"]
    env_file: [.env]
    networks: [default]
    depends_on: [worker]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: [.env]
    volumes:
      - ./tasks:/app/tasks
networks:
  default:
    driver: bridge