version: "3.8"

services:
  worker:
    build:
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - /Users/ampersandor/data/sat:/data
      - ../tasks:/app/tasks
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - default

  flower:
    image: mher/flower
    command: ["celery", "--broker=${BROKER_URL}", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - worker

networks:
  default:
    driver: bridge